title: Kavana Manvi Krishnamurthy
logo: images/dp3.jpg
description: >
  The secret ingredient behind my great coding skills is love — and a lot of discipline!  
  I bring a solid foundation in software engineering from my time at Oracle and a Master’s in Computer Science. 
  I’m passionate about Machine Learning, Data Analytics, and solving tough problems (300+ on LeetCode!).
theme: jekyll-theme-minimal


