title: Kavana Manvi Krishnamurthy
logo: images/dp3.jpg
description: The secret ingredient behind my great coding skills is - love.  Also discipline and consistency.  I am passionate about Machine Learning, Data Analytics, and solving tough problems (300+ on LeetCode!).
#show_downloads: true
theme: jekyll-theme-minimal

